import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { createShutTheBoxDepedencies } from "../games/ShutTheBox";
import { App } from "../games/ShutTheBox/App";

const inter = Inter({ subsets: ["latin"] });

const appDependencies = createShutTheBoxDepedencies();

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <App appDependencies={appDependencies} />
      </main>
    </>
  );
}
